import fs from 'node:fs';
import path from 'node:path';

import {
  CJS_INTEROP_ARTIFACTS,
  IMPLEMENTED_SUBPATHS,
  ORACLE_SPECIFIERS,
  OUT_OF_SCOPE_SUBPATHS,
  importedNames,
  readFunctionalExports,
  readManifest,
} from './export-names.mjs';

/**
 * M20 certification matrix. For every oracle export of every implemented
 * subpath: is it exported, and which differential suites exercise the oracle
 * name? Coverage is read from the suites themselves — the `rxjs` /
 * `rxjs/operators` / `rxjs/testing` import lists of
 * `test/differential/*.test.mjs` — so the matrix is derived, never
 * hand-maintained. The two CommonJS interop artifacts are certified by the
 * package gate instead. Every exported name must be certified; the tool
 * writes `docs/CERTIFICATION-MATRIX.md` and regenerates
 * `feature-parity-list.md`, then fails on any gap.
 */
const manifest = readManifest();
const functionalExports = readFunctionalExports();
const suiteDirectory = path.resolve('test/differential');
const subpaths = Object.keys(IMPLEMENTED_SUBPATHS);

const coverage = Object.fromEntries(subpaths.map((subpath) => [subpath, new Map()]));
const subpathBySpecifier = Object.fromEntries(subpaths.map((subpath) => [ORACLE_SPECIFIERS[subpath], subpath]));
const specifierAlternatives = Object.values(ORACLE_SPECIFIERS)
  .map((specifier) => specifier.replace(/[/]/g, '\\/'))
  .join('|');
const importPattern = new RegExp(`import\\s*\\{([^}]*)\\}\\s*from\\s*'(${specifierAlternatives})'`, 'g');
for (const file of fs.readdirSync(suiteDirectory).filter((name) => name.endsWith('.test.mjs')).sort()) {
  const source = fs.readFileSync(path.join(suiteDirectory, file), 'utf8');
  const suite = file.replace(/\.test\.mjs$/, '');
  for (const match of source.matchAll(importPattern)) {
    const subpath = subpathBySpecifier[match[2]];
    for (const specifier of match[1].split(',')) {
      const name = specifier.trim().split(/\s+as\s+/)[0].trim();
      if (!name) continue;
      if (!coverage[subpath].has(name)) coverage[subpath].set(name, new Set());
      coverage[subpath].get(name).add(suite);
    }
  }
}

const rows = {};
const gaps = [];
for (const [subpath, specifier] of Object.entries(IMPLEMENTED_SUBPATHS)) {
  const actual = new Set(await importedNames(specifier));
  rows[subpath] = manifest.exports[subpath].map((name) => {
    const exported = actual.has(name);
    let suites;
    if (CJS_INTEROP_ARTIFACTS.includes(name)) {
      suites = ['package gate (`tools/check-package.mjs`)'];
    } else {
      // A root operator re-exported on the subpath is certified by the root suites.
      const own = coverage[subpath].get(name) ?? new Set();
      const inherited = subpath === './operators' ? coverage['.'].get(name) ?? new Set() : new Set();
      suites = [...new Set([...own, ...inherited])].sort();
    }
    if (exported && suites.length === 0) gaps.push(`${subpath} ${name}`);
    if (!exported) gaps.push(`${subpath} ${name} (not exported)`);
    return { name, exported, suites };
  });
}

const percent = (count, total) => ((count / total) * 100).toFixed(1);
const implemented = (subpath) => rows[subpath].filter((row) => row.exported).length;
const certified = (subpath) => rows[subpath].filter((row) => row.exported && row.suites.length).length;
const total = (subpath) => rows[subpath].length;
const suiteCount = new Set(
  Object.values(coverage).flatMap((map) => [...map.values()].flatMap((set) => [...set]))
).size;

const surfaceLabel = (subpath) => (subpath === '.' ? '`.` (root)' : `\`${subpath}\``);
const summaryRow = (subpath) =>
  `| ${surfaceLabel(subpath)} | ${implemented(subpath)} / ${total(subpath)} (${percent(implemented(subpath), total(subpath))}%) | ${certified(subpath)} / ${total(subpath)} |`;
const table = (subpath) =>
  rows[subpath]
    .map(
      (row) =>
        `| \`${row.name}\` | ${row.exported ? '✅' : '—'} | ${row.suites.length ? row.suites.join(', ') : '⚠ none'} |`
    )
    .join('\n');

const matrix = `# Certification Matrix

Generated by \`tools/certification-matrix.mjs\` (M20) from \`reference/exports.json\`,
Node's view of the built package, and the oracle import lists of the
differential suites under \`test/differential/\`. Do not edit by hand.

| Surface | Exported | Certified |
| --- | --- | --- |
${subpaths.map(summaryRow).join('\n')}

A name is *certified* when at least one differential suite imports it from
the oracle package and traces it against this implementation (the two
CommonJS interop artifacts are certified by the package gate). ${suiteCount}
differential suites contribute. Out-of-scope oracle subpaths — separate
feature surfaces over host I/O: ${OUT_OF_SCOPE_SUBPATHS.map((s) => `\`${s}\``).join(', ')}.

## Root exports (\`rxjs\`)

| Export | Status | Differential suites |
| --- | --- | --- |
${table('.')}

## Subpath exports (\`rxjs/operators\`)

Names shared with the root are certified by the root suites; the seven
operator-form names (\`combineLatest\`, \`concat\`, \`merge\`, \`zip\`, \`race\`,
\`partition\`, \`onErrorResumeNext\`) are traced separately.

| Export | Status | Differential suites |
| --- | --- | --- |
${table('./operators')}

## Subpath exports (\`rxjs/testing\`)

The marble-testing surface (M21): \`TestScheduler\` is traced by the
\`testing\` suite against the oracle's own \`TestScheduler\`.

| Export | Status | Differential suites |
| --- | --- | --- |
${table('./testing')}

## Functional root extensions

Tracked separately, never counted as parity: ${functionalExports.map((name) => `\`${name}\``).join(', ')}.
`;

fs.writeFileSync(path.resolve('docs/CERTIFICATION-MATRIX.md'), matrix);

const parityList = `# Feature Parity List

Root export parity of \`rxjs-pure-fp\` against the pinned behavioral oracle
\`rxjs@7.8.2\`, generated from \`reference/exports.json\` and Node's view of the
built package by \`tools/certification-matrix.mjs\` after **M20 — Differential
Certification** (M21 adds the \`rxjs/testing\` subpath).

**Implemented: ${implemented('.')} / ${total('.')} root exports (${percent(implemented('.'), total('.'))}%)** — 0 unexpected exports.
The \`rxjs/operators\` subpath is provided as well: ${implemented('./operators')} / ${total('./operators')} names,
and the \`rxjs/testing\` subpath: ${implemented('./testing')} / ${total('./testing')} names.

An implemented name means the export exists with differentially certified
behavior for its claimed scope (see \`docs/RXJS-7.8.2-PARITY.md\` for
per-milestone certified scope and recorded deviations, and
\`docs/CERTIFICATION-MATRIX.md\` for the per-name certification evidence).

| Implemented (rxjs-pure-fp) | Original (rxjs@7.8.2) |
| --- | --- |
${rows['.'].map((row) => `| ${row.exported ? `\`${row.name}\` ✅` : '—'} | \`${row.name}\` |`).join('\n')}

## \`rxjs/testing\` subpath

| Implemented (rxjs-pure-fp/testing) | Original (rxjs/testing) |
| --- | --- |
${rows['./testing'].map((row) => `| ${row.exported ? `\`${row.name}\` ✅` : '—'} | \`${row.name}\` |`).join('\n')}

## Deliberate functional extensions (not counted as parity)

| Extension export |
| --- |
${functionalExports.map((name) => `| \`${name}\` |`).join('\n')}
`;

fs.writeFileSync(path.resolve('feature-parity-list.md'), parityList);

console.log(
  `Certification matrix: ${subpaths
    .map((subpath) => `${subpath === '.' ? 'root' : subpath.slice(2)} ${implemented(subpath)}/${total(subpath)}`)
    .join(', ')}, ${suiteCount} suites.`
);
if (gaps.length) {
  console.error(`Certification gaps (${gaps.length}):\n- ${gaps.join('\n- ')}`);
  process.exit(1);
}
console.log('Every exported oracle name is differentially certified.');
